---
- name: ensure that software-properties-common is installed if needed
  apt: 
    pkg: software-properties-common
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  when: ansible_distribution_release == "precise"

- name: ensure that ubuntu cloud archive is available if needed
  command: apt-add-repository cloud-archive:icehouse
  when: ansible_distribution_release == "precise"
  
- name: ensure keystone packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - keystone
    - python-keystoneclient
    - python-mysqldb

- name: ensure keystone is started and enabled
  service: 
    name: keystone
    state: started 
    enabled: yes

- name: install script for cron job to periodically flush expired tokens
  copy:
    content: "#!/bin/sh\n/usr/bin/keystone-manage token_flush\n"
    dest: /etc/cron.daily/keystone-token-flush
    owner: root
    group: root
    mode: 0755
