---
- name: ensure openstack keystone requirements packages are installed
  action: "{{ openstack_keystone_package_info.pkg_mgr }}"
  args: openstack_keystone_package_info.args
  with_items: openstack_keystone_package_info.pre_pkgs
  when: openstack_keystone_package_info.pre_pkgs|length > 0

- name: ensure openstack repository is enabled
  action: "{{ openstack_keystone_repo_info.pkg_repo }}"
  args: openstack_keystone_repo_info.args
  with_items: openstack_keystone_repo_info.repos
  when: openstack_keystone_repo_info.repos|length > 0

- name: ensure openstack keystone packages are installed
  action: "{{ openstack_keystone_package_info.pkg_mgr }}"
  args: openstack_keystone_package_info.args
  with_items: openstack_keystone_package_info.pkgs
  when: openstack_keystone_package_info.pkgs|length > 0

- name: ensure keystone services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: openstack_keystone_services

- name: install script for cron job to periodically flush expired tokens
  copy:
    content: "#!/bin/sh\n/usr/bin/keystone-manage token_flush\n"
    dest: /etc/cron.daily/keystone-token-flush
    owner: root
    group: root
    mode: 0755
