---
- name: wait until keystone service is ready
  wait_for:
    delay: 1
    host: "{{ openstack_identity_endpoint_host }}"
    port: 35357
    state: started

- name: ensure admin tenant has been created
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    tenant_description: "Admin Tenant"

- name: ensure admin user has been created
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    user: admin
    password: "{{ openstack_identity_admin_password }}"

- name: ensure admin role has been created and associated with admin user
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    user: admin
    role: admin

- name: ensure _member_ role has been created and associated with admin user
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    user: admin
    role: _member_

- name: ensure service tenant has been created
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: service
    tenant_description: "Service Tenant"

- name: ensure keystone endpoint information has been added to keystone
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_service:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    region: "{{ openstack_identity_region }}"
    name: keystone
    type: identity
    description: "Identity Service"
    public_url: "{{ openstack_identity_public_url }}"
    internal_url: "{{ openstack_identity_internal_url }}"
    admin_url: "{{ openstack_identity_admin_url }}"
