---
# FIXME: creation of admin tenant should go into configuration phase?

- name: create admin tenant
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    tenant_description: "Admin Tenant"

- name: create admin user
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    user: admin
    password: "{{ openstack_identity_admin_password }}"

- name: create admin role and associate it with admin user
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    user: admin
    role: admin

- name: associate _member_ role with the admin user
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    user: admin
    role: _member_

- name: create service tenant
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: service
    tenant_description: "Service Tenant"

- name: add keystone endpoint information
  keystone_service:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    region: "{{ openstack_default_region }}"
    name: keystone
    type: identity
    description: "Identity Service"
    public_url: "{{ openstack_identity_public_url }}"
    internal_url: "{{ openstack_identity_internal_url }}"
    admin_url: "{{ openstack_identity_admin_url }}"
