---
- name: wait until keystone service is ready
    wait_for:
      delay: 1
      host: "{{ openstack_identity_endpoint_host }}"
      port: 35357
      state: started

- name: create admin tenant
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    tenant_description: "Admin Tenant"

- name: create admin user
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    user: admin
    password: "{{ openstack_identity_admin_password }}"

- name: create admin role and associate it with admin user
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    user: admin
    role: admin

- name: associate _member_ role with the admin user
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    user: admin
    role: _member_

- name: create service tenant
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: service
    tenant_description: "Service Tenant"

- name: add keystone endpoint information
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_service:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    region: "{{ openstack_identity_region }}"
    name: keystone
    type: identity
    description: "Identity Service"
    public_url: "{{ openstack_identity_public_url }}"
    internal_url: "{{ openstack_identity_internal_url }}"
    admin_url: "{{ openstack_identity_admin_url }}"
